#!/bin/sh
export REDIS_HOST=${REDIS_HOST:-redis.default.svc.cluster.local}
export REDIS_PORT=${REDIS_PORT:-6379}

export CMD="redis-cli -h ${REDIS_HOST} -p ${REDIS_PORT}"

if [ "${REDIS_PASSWORD_FILE}" != "" ]; then
  export REDIS_PASSWORD=`cat ${REDIS_PASSWORD_FILE}`
fi

if [ "${REDIS_PASSWORD}" != "" ]; then
  export CMD="${CMD} --no-auth-warning -a ${REDIS_PASSWORD}"
fi

# execute
echo "Executing: ${CMD}"
${CMD}
