#!/bin/sh
export MYSQL_HOST=${MYSQL_HOST:-mysql.default.svc.cluster.local}
export MYSQL_PORT=${MYSQL_PORT:-3306}
export MYSQL_USER=${MYSQL_USER:-root}

if [ "${MYSQL_PWD_FILE}" != "" ]; then
  export MYSQL_PWD=`cat ${MYSQL_PWD_FILE}`
fi

if [ "${MYSQL_PWD}" == "" ]; then
  echo "MYSQL_PWD must be set"
  exit 1
fi

export CMD="mysql -h ${MYSQL_HOST} -P ${MYSQL_PORT} -u${MYSQL_USER}"

if [ "${MYSQL_DATABASE}" != "" ]; then
  export CMD="${CMD} -D ${MYSQL_DATABASE}"
fi

if [ "${MYSQL_OPTS}" != "" ]; then
  export CMD="${CMD} ${MYSQL_OPTS}"
fi

# execute
echo "Executing: ${CMD}"
${CMD}
